### PR TITLE
safe get key for request.META

### PR DESCRIPTION
**Pull request by talbenbasat**

### CODE REVIEW

**Comment by talbenbasat** [comment]
@anx-ckreuzberger can you please check and merge

**Comment by anx-ckreuzberger** [comment]
PR looks fine, but I'm not sure if this is a behaviour that I would want to support without notifying the dev/admin about it.

I think I'll make those "default values" configureable in Django Settings.

**Comment by talbenbasat** [comment]
sounds good added those values..
let me know if there's any why I can help

**Comment by anx-ckreuzberger** [comment]
Thanks!

**Comment by vonorm** [comment]
It might better to allow users to set the name of the header rather than providing default values if the `REMOTE_ADDR` is not found?

E.g. so essentially allowing to user to say "hey use HTTP_X_REAL_IP not REMOTE_ADDR please"

**Comment by anx-ckreuzberger** [comment]
I believe the implementation suggested by @vonorm is correct, the implementation coming from the Merge Request is faulty.

**Pull request merged**
