### PR TITLE
Proper validation errors and browsable api

### PR DESCRIPTION
**Pull request by anx-ckreuzberger**
This fixes issue #19.

We now have beautiful "browsable error messages" (patent pending?).

screenshot from 2019-02-18 15-03-39
screenshot from 2019-02-18 15-03-50

### CODE REVIEW

**Comment by anx-ckreuzberger** [comment]
In addition, I changed from APIView to GenericAPIView which enables great swagger support:
screenshot from 2019-02-18 15-18-37

**Comment by thapabishwa** [comment]
Just a query: When would do you plan to create a release for the changes reflected in this PR?

**Comment by anx-ckreuzberger** [comment]
I'm planning to release it today as version 1.0.0alpha1

**Comment by thapabishwa** [comment]
Thanks @anx-ckreuzberger . Looking forward to use the latest release. :)

**Pull request merged**
