### PR TITLE
Strengthen the password validator by using it in the APIView

### PR DESCRIPTION
**Pull request by thapabishwa**
As per the the name of pull request, validating password in the APIView makes more sense as we are able to access the user. This allows us to validate password against UserAttributeSimilarityVlidator, MinimumLengthValidator, CommonPasswordValidator, NumericPasswordValidator or any other custom validators that have been defined in the project config under ```AUTH_PASSWORD_VALIDATORS```.

For ex:
```
    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
            'OPTIONS': {
                'min_length': 12,
            }
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]
```

### CODE REVIEW

**Comment by anx-ckreuzberger** [comment]
Thank you for the PR, looks good.

Tests in travis-ci seem to be failing because of some random number bullshit, so that's fine.

**Comment by thapabishwa** [comment]
I tried fixing it but had no luck.

**Comment by anx-ckreuzberger** [comment]
That's fine, it's already merged ;)

I have a random token generator, and it checks that no two tokens are the same. Sometimes they are, then it just helps to restart the test (which I did).

**Comment by thapabishwa** [comment]
When will you be able to make a release candidate for the changes?

**Comment by anx-ckreuzberger** [comment]
it's in 1.0.0a2

```
pip install django-rest-passwordreset==1.0.0a2
```

**Comment by thapabishwa** [comment]
My bad, should have checked the releases before I shouted here.

**Comment by anx-ckreuzberger** [comment]
I just noticed that
```python
            except ValidationError as e:
                raise serializers.ValidationError(e.messages)
```
returns the validation error as a list, rather than a dictionary with `password` as the key.
I will change this behaviour, such that it is compatible with the previous approach
```javascript
{
    "password": ["something", "something else"]
}
```

**Comment by anx-ckreuzberger** [comment]
See https://github.com/anx-ckreuzberger/django-rest-passwordreset/commit/53123f94b42f5ad918f1ec7d339623d3752ce961 for details

**Pull request merged**
